name: Test save cache functionalities

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      image_os:
        required: true
        type: string
      arch:
        required: true
        type: string

jobs:
  test:
    name: ${{ inputs.image_os }} ${{ inputs.arch }} save cache
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: false
          cache-to: type=gha,mode=max
