name: Test cache functionalities

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      image_os:
        required: true
        type: string
      arch:
        required: true
        type: string

jobs:
  test:
    name: ${{ inputs.image_os }} ${{ inputs.arch }} cache
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
