name: Test save cache functionalities

on:
  workflow_dispatch:

jobs:
  test:
    name: Docker layer save cache
    runs-on: ubicloud-standard-2-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: false
          cache-to: type=gha,mode=max

      - name: Cat docker layer cache
        run: sudo cat /var/log/cacheproxy.log
        if: always()
